### PR TITLE
Bug fix #54 for the reactive flow

### LINKED ISSUE #54: Single virtual list get operations doesn't solve dependencies
Currently only multi-operations support solving dependencies, if you use single virtual list get operations you won't receive nested objects in the results.

for example, running:
```java
results = list.getByKey(102, ReturnType.DEFAULT);
```

results:
```java
{id=102, name=bob, date=12345, thisC=null, listC=[null, null]}
```

which at the moment isn't the same running:
```java
results = (List<B>) list.beginMultiOperation()
				.getByKey(102)
				.end();
```

results:
```java
{id=102, name=bob, date=12345, thisC={1,"a"}, listC=[{2,"b"}, {3,"c"}]}
```

The multi-operations solves the dependencies (nested objects), and single-operations should do the same.
* This applies to the reactive flow as well.

### PR DESCRIPTION
**Pull request by roimenashe**
for the reactive flow.
+ a minor fix in the non-reactive flow size() method - return -1L instead of null.

### CODE REVIEW

File: src/main/java/com/aerospike/mapper/tools/virtuallist/ReactiveVirtualList.java [hunk 1]
```diff
@@ -84,7 +85,13 @@ public ReactiveVirtualList(@NotNull IReactiveAeroMapper reactiveAeroMapper, @Not
...
         return reactiveAeroMapper.getReactorClient()
                 .operate(writePolicy, key, interactor.getOperation())
-                .map(keyRecord -> (E)interactor.getResult(keyRecord.record.getList(binName)));
+                .map(keyRecord -> {
+                    E result = keyRecord == null ? null : (E) interactor.getResult(keyRecord.record.getList(binName));
+                    if (result != null) {
+                        reactiveAeroMapper.getMappingConverter().resolveDependencies(ClassCache.getInstance().loadClass(result.getClass(), reactiveAeroMapper));
+                    }
+                    return result;
+                });
```
Comment (reugn) [inline src/main/java/com/aerospike/mapper/tools/virtuallist/ReactiveVirtualList.java:94]: Worth extracting this to a method, to avoid code duplication.

Comment (roimenashe) [reply src/main/java/com/aerospike/mapper/tools/virtuallist/ReactiveVirtualList.java]: Agree, done.

**Review by reugn — APPROVED** [review]

**Review by tfaulkes — APPROVED** [review]
